OSOE-46: Adding reverse proxy service.
Lombiq/Testing-Toolbox pull request #20
Opened 2022-07-24 20:35 UTC by dministro

OSOE-46

2022-09-27 22:53 UTC, DAud-IcI requested changes

2022-09-27 22:53 UTC, DAud-IcI commented on Integration/Services/IProxyConnectionProvider.cs
> +    string BaseAddress { get; }
Shouldn't this be `Uri` since it's a base URL? I see the implementation uses `uri.ToString()` anyway.

2022-09-27 22:53 UTC, DAud-IcI commented on Integration/Services/TestReverseProxy.cs
> +                var httpForwarder = builder.ApplicationServices.GetService<IHttpForwarder>();
Always use `GetRequiredService` unless the service is optional. (`GetService` returns `null` if the service is not found, then you get a hard to debug NRE when you try to use it. If you intentionally want an optional service, then check for null whenever you use it but I don't think that's the case here.)
```suggestion
                var httpForwarder = builder.ApplicationServices.GetRequiredService<IHttpForwarder>();
```

2022-09-27 22:53 UTC, DAud-IcI commented on Integration/Services/TestReverseProxy.cs
> +        _proxyConnectionProvider = null;
Why not a single `public void AttachConnectionProvider(IProxyConnectionProvider clientConnectionProvider = null)` constructor?

2022-09-27 22:53 UTC, DAud-IcI commented on Integration/Services/TestReverseProxy.cs
> +            throw new InvalidOperationException("Instance not started.");
```suggestion
            throw new InvalidOperationException("The instance has not been not started.");
```

2022-09-27 22:53 UTC, DAud-IcI commented on Integration/Services/TestReverseProxy.cs
> +        }
```suggestion
        if (_disposed || _disposedAsync) return;

        if (_webHost != null) await StopAsync().ConfigureAwait(false);
```

2022-09-29 16:10 UTC, dministro commented on Integration/Services/TestReverseProxy.cs
> +        _proxyConnectionProvider = null;
More readable than:
Attaching: `proxyInstance.AttachConnectionProvider(connectionProvider)`
Detaching: `proxyInstance.AttachConnectionProvider()`

2022-09-29 16:11 UTC, DAud-IcI commented on Integration/Services/TestReverseProxy.cs
> +        _proxyConnectionProvider = null;
Ah, the names are different! Never mind, looks like I can't read 😂

2022-10-14 08:24 UTC, merged